//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendEmailAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagory_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catagory_tbl()
        {
            this.Symbols_tbl = new HashSet<Symbols_tbl>();
        }
    
        public int CatagoryCode { get; set; }
        public string CatagoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symbols_tbl> Symbols_tbl { get; set; }
    }
}
