//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendEmailAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contacts_tbl()
        {
            this.Message_tbl = new HashSet<Message_tbl>();
        }
    
        public int Code { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string E_Mail { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message_tbl> Message_tbl { get; set; }
    }
}
