//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendEmailAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_tbl
    {
        public int MessageId { get; set; }
        public int ReceiveId { get; set; }
        public string SenderId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IsSucsses { get; set; }
    
        public virtual Contacts_tbl Contacts_tbl { get; set; }
        public virtual Users_tbl Users_tbl { get; set; }
    }
}
