//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendEmailAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class symbolsEntities1 : DbContext
    {
        public symbolsEntities1()
            : base("name=symbolsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catagory_tbl> Catagory_tbl { get; set; }
        public virtual DbSet<Contacts_tbl> Contacts_tbl { get; set; }
        public virtual DbSet<Message_tbl> Message_tbl { get; set; }
        public virtual DbSet<Symbols_tbl> Symbols_tbl { get; set; }
        public virtual DbSet<Users_tbl> Users_tbl { get; set; }
    }
}
