//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendEmailAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbols_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Symbols_tbl()
        {
            this.Catagory_tbl = new HashSet<Catagory_tbl>();
        }
    
        public int SymbolCode { get; set; }
        public string Image { get; set; }
        public string Word { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catagory_tbl> Catagory_tbl { get; set; }
    }
}
